import React from 'react';
import { AnimatedSection } from './AnimatedSection';
import { Sparkles, Smartphone, ArrowRight, SlidersHorizontal } from 'lucide-react';

const FUTURES: Array<{
  icon: React.ElementType;
  title: string;
  blurb: string;
  status: 'ready' | 'soon';
  href?: string;
}> = [
  {
    icon: SlidersHorizontal,
    title: 'WHAT-IF SIMULATOR',
    blurb: 'Change attendance, clear a backlog, shift mid marks — see the CGPA impact before it happens.',
    status: 'ready',
    href: '/app/what-if',
  },
  {
    icon: Sparkles,
    title: 'PRESCRIPTIVE RECOMMENDATIONS',
    blurb: 'Actionable next-semester moves ranked by their expected impact on your risk profile.',
    status: 'ready',
    href: '/app/recommendations',
  },
  {
    icon: Smartphone,
    title: 'AI ACADEMIC ASSISTANT',
    blurb: 'Ask grounded questions about your verified record — predictions are generated by the ML engines, never by the assistant.',
    status: 'ready',
    href: '/app/assistant',
  },
  {
    icon: ArrowRight,
    title: 'FACULTY INTELLIGENCE & INTERVENTIONS',
    blurb: 'Prioritized risk queues, alerts, and tracked interventions with before/after outcome comparisons.',
    status: 'ready',
    href: '/faculty',
  },
  {
    icon: SlidersHorizontal,
    title: 'INSTITUTION ANALYTICS',
    blurb: 'Department, semester, alert, and intervention analytics for administrators.',
    status: 'ready',
    href: '/faculty/analytics',
  },
  {
    icon: Smartphone,
    title: 'MOBILE EXPERIENCE',
    blurb: 'The full explainable dashboard, optimized for on-the-go review.',
    status: 'ready',
  },
];

/** Honest feature grid — every card links to a shipped, authenticated page. */
export const FuturePreview: React.FC = () => {
  return (
    <AnimatedSection id="future" className="feature-section">
      <div className="section-label" style={{ textAlign: 'center' }}>
        <span className="mono-label">FEATURE GRID</span>
        <h2>WHAT IS LIVE</h2>
      </div>
      <div className="future-grid">
        {FUTURES.map((f) => (
          <div key={f.title} className="future-card">
            <span className={`node-status-chip ${f.status}`}>
              {f.status === 'ready' ? 'AVAILABLE NOW' : 'IN DEVELOPMENT'}
            </span>
            <f.icon size={22} style={{ color: 'var(--color-primary)' }} />
            <span className="future-title">{f.title}</span>
            <span className="future-blurb">{f.blurb}</span>
            {f.href && (
              <a href={f.href} className="btn btn-outline btn-sm">
                OPEN <ArrowRight size={13} />
              </a>
            )}
          </div>
        ))}
      </div>
    </AnimatedSection>
  );
};