"""
Deterministic Recommendation Rules Engine for Phase 8.

Translates verified multi-phase academic evidence (Data, ML Predictions, Risk Factors,
SHAP Explanations, What-If Simulations) into ranked, personalized, actionable recommendations.

Rules:
1. AttendanceRecommendationRule
2. BacklogRecommendationRule
3. MidtermExamRecommendationRule
4. InternalAssessmentRecommendationRule
5. AcademicTrendRecommendationRule
6. StrengthMaintenanceRule
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional
import math

from ml.recommendations.recommendation_config import (
    RecommendationCategory,
    RecommendationPriority,
    RecommendationSource,
    ExpectedImpact,
    TimeHorizon,
    RecommendationPolicyConfig,
    PRIORITY_SEVERITY_ORDER,
)


class CandidateEvidence:
    """Represents a discrete piece of evidence supporting a recommendation."""
    def __init__(
        self,
        factor: str,
        display_name: str,
        current_value: Optional[Any],
        target_or_threshold: Optional[Any],
        unit: str,
        source: RecommendationSource,
        simulated_value: Optional[Any] = None,
        shap_contribution: Optional[float] = None,
        impact_detail: Optional[str] = None,
    ):
        self.factor = factor
        self.display_name = display_name
        self.current_value = current_value
        self.target_or_threshold = target_or_threshold
        self.unit = unit
        self.source = source
        self.simulated_value = simulated_value
        self.shap_contribution = shap_contribution
        self.impact_detail = impact_detail

    def to_dict(self) -> Dict[str, Any]:
        return {
            "factor": self.factor,
            "display_name": self.display_name,
            "current_value": self.current_value,
            "target_or_threshold": self.target_or_threshold,
            "unit": self.unit,
            "source": self.source.value,
            "simulated_value": self.simulated_value,
            "shap_contribution": self.shap_contribution,
            "impact_detail": self.impact_detail,
        }


class CandidateRecommendation:
    """Candidate recommendation generated by a rule before final ranking and filtering."""
    def __init__(
        self,
        id: str,
        title: str,
        priority: RecommendationPriority,
        category: RecommendationCategory,
        evidence: List[CandidateEvidence],
        action: str,
        expected_impact: ExpectedImpact,
        source: RecommendationSource,
        time_horizon: TimeHorizon,
        risk_factor: Optional[str] = None,
        technical_details: Optional[Dict[str, Any]] = None,
        ranking_score: float = 0.0,
    ):
        self.id = id
        self.title = title
        self.priority = priority
        self.category = category
        self.evidence = evidence
        self.action = action
        self.expected_impact = expected_impact
        self.source = source
        self.time_horizon = time_horizon
        self.risk_factor = risk_factor
        self.technical_details = technical_details or {}
        self.ranking_score = ranking_score

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "priority": self.priority.value,
            "category": self.category.value,
            "evidence": [e.to_dict() for e in self.evidence],
            "action": self.action,
            "expected_impact": self.expected_impact.value,
            "source": self.source.value,
            "time_horizon": self.time_horizon.value,
            "risk_factor": self.risk_factor,
            "technical_details": self.technical_details,
        }


class BaseRecommendationRule(ABC):
    """Abstract base class for evidence-driven recommendation rules."""
    @abstractmethod
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        """Evaluates inputs and returns a CandidateRecommendation if applicable, else None."""
        pass

    @staticmethod
    def _extract_shap_for_feature(explanation: Optional[Any], feature_name: str) -> Optional[float]:
        """Extracts SHAP value for a given feature from Phase 5 explanation schema or dict."""
        if not explanation:
            return None
        factors = []
        if hasattr(explanation, "top_factors"):
            factors = getattr(explanation, "top_factors", [])
        elif isinstance(explanation, dict) and "top_factors" in explanation:
            factors = explanation["top_factors"]

        for f in factors:
            fname = f.feature_name if hasattr(f, "feature_name") else f.get("feature_name", "")
            if fname == feature_name:
                val = f.shap_value if hasattr(f, "shap_value") else f.get("shap_value", None)
                return round(float(val), 4) if val is not None else None
        return None

    @staticmethod
    def _determine_simulation_impact(simulation_delta: Optional[Dict[str, Any]]) -> ExpectedImpact:
        """Determines evidence-backed impact level from actual What-If simulation deltas."""
        if not simulation_delta:
            return ExpectedImpact.UNKNOWN

        cgpa_delta = simulation_delta.get("cgpa_delta", 0.0)
        risk_score_delta = simulation_delta.get("risk_score_delta", 0.0)  # negative means risk reduced

        if (
            cgpa_delta >= RecommendationPolicyConfig.SIMULATION_HIGH_IMPACT_CGPA_DELTA
            or risk_score_delta <= -RecommendationPolicyConfig.SIMULATION_HIGH_IMPACT_RISK_SCORE_DELTA
        ):
            return ExpectedImpact.HIGH
        elif (
            cgpa_delta >= RecommendationPolicyConfig.SIMULATION_MED_IMPACT_CGPA_DELTA
            or risk_score_delta <= -RecommendationPolicyConfig.SIMULATION_MED_IMPACT_RISK_SCORE_DELTA
        ):
            return ExpectedImpact.MEDIUM
        elif cgpa_delta > 0.0 or risk_score_delta < 0.0:
            return ExpectedImpact.LOW

        return ExpectedImpact.UNKNOWN


# ---------------------------------------------------------------------------
# Rule 1: Attendance Recommendation
# ---------------------------------------------------------------------------

class AttendanceRecommendationRule(BaseRecommendationRule):
    """
    Evaluates attendance evidence against institutional policy thresholds,
    SHAP contributions, and What-If attendance simulation results.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        attendance = raw_data.get("attendance_percentage")
        if attendance is None:
            return None

        att_val = float(attendance)
        shap_val = self._extract_shap_for_feature(explanation, "attendance_percentage")
        sim_delta = simulation_data.get("attendance") if simulation_data else None

        # Check if attendance is below institutional target
        if att_val >= RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET:
            return None

        # Determine priority based on policy + risk + SHAP
        if att_val < RecommendationPolicyConfig.ATTENDANCE_CRITICAL_THRESHOLD:
            priority = RecommendationPriority.CRITICAL
            action = (
                f"Your current attendance ({att_val:.1f}%) is below the critical threshold of "
                f"{RecommendationPolicyConfig.ATTENDANCE_CRITICAL_THRESHOLD}%. Prioritize immediate, "
                f"unbroken attendance in all remaining lecture and lab sessions to reach the safe target "
                f"of {RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET}%."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 40.0 + (RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET - att_val)
        elif att_val < RecommendationPolicyConfig.ATTENDANCE_WARNING_THRESHOLD:
            priority = RecommendationPriority.HIGH
            action = (
                f"Your attendance ({att_val:.1f}%) is below the institutional requirement of "
                f"{RecommendationPolicyConfig.ATTENDANCE_WARNING_THRESHOLD}%. Attend all upcoming "
                f"scheduled classes to avoid examination eligibility flags and reach {RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET}%."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 30.0 + (RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET - att_val)
        else:
            priority = RecommendationPriority.MEDIUM
            action = (
                f"Attendance ({att_val:.1f}%) is satisfactory but below the optimal safe target "
                f"({RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET}%). Maintain steady attendance to protect academic standing."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 20.0 + (RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET - att_val)

        # Elevate priority if SHAP negative contribution is strong
        if shap_val is not None and shap_val < -0.2:
            if priority == RecommendationPriority.MEDIUM:
                priority = RecommendationPriority.HIGH
            ranking_score += abs(shap_val) * 10.0

        # Expected impact from real simulation
        impact = self._determine_simulation_impact(sim_delta)
        if impact == ExpectedImpact.UNKNOWN:
            impact = ExpectedImpact.HIGH if att_val < RecommendationPolicyConfig.ATTENDANCE_CRITICAL_THRESHOLD else ExpectedImpact.MEDIUM

        # Determine source
        sources = [RecommendationSource.ACADEMIC_DATA, RecommendationSource.RISK_POLICY]
        if shap_val is not None:
            sources.append(RecommendationSource.XAI)
        if sim_delta:
            sources.append(RecommendationSource.WHAT_IF_SIMULATION)
        source = RecommendationSource.COMBINED if len(sources) > 1 else sources[0]

        impact_detail = None
        sim_val = None
        if sim_delta:
            sim_val = sim_delta.get("simulated_value")
            cgpa_diff = sim_delta.get("cgpa_delta", 0.0)
            trans = sim_delta.get("risk_transition", "")
            impact_detail = f"Simulating attendance to {sim_val}% yields +{cgpa_diff:.2f} predicted CGPA ({trans})."

        evidence = [
            CandidateEvidence(
                factor="attendance_percentage",
                display_name="Class Attendance",
                current_value=round(att_val, 1),
                target_or_threshold=RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET,
                unit="%",
                source=source,
                simulated_value=sim_val,
                shap_contribution=shap_val,
                impact_detail=impact_detail,
            )
        ]

        return CandidateRecommendation(
            id="rec-attendance-improvement",
            title="Improve Class Attendance",
            priority=priority,
            category=RecommendationCategory.ATTENDANCE,
            evidence=evidence,
            action=action,
            expected_impact=impact,
            source=source,
            time_horizon=time_horizon,
            risk_factor="Attendance",
            technical_details={
                "threshold_checked": RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET,
                "shap_contribution": shap_val,
                "simulation_applied": bool(sim_delta),
            },
            ranking_score=ranking_score,
        )


# ---------------------------------------------------------------------------
# Rule 2: Backlog Recovery Recommendation
# ---------------------------------------------------------------------------

class BacklogRecommendationRule(BaseRecommendationRule):
    """
    Evaluates backlog count against institutional risk policy,
    SHAP contributions, and backlog clearance simulations.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        backlogs = raw_data.get("backlogs")
        if backlogs is None:
            return None

        bl_count = int(backlogs)
        if bl_count <= 0:
            return None

        shap_val = self._extract_shap_for_feature(explanation, "backlogs")
        sim_delta = simulation_data.get("backlogs") if simulation_data else None

        if bl_count >= RecommendationPolicyConfig.BACKLOG_CRITICAL_THRESHOLD:
            priority = RecommendationPriority.CRITICAL
            action = (
                f"You have {bl_count} active course backlogs, which severely impacts academic trajectory and "
                f"graduation progress. Formulate a structured backlog clearance plan with your academic advisor, "
                f"registering for the earliest available supplementary or remedial examinations."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 50.0 + bl_count * 5.0
        elif bl_count >= RecommendationPolicyConfig.BACKLOG_WARNING_THRESHOLD:
            priority = RecommendationPriority.CRITICAL
            action = (
                f"You have {bl_count} active backlog(s). Focus targeted preparation on outstanding subjects "
                f"and register for upcoming remedial or clearance exam windows to restore good standing."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 45.0 + bl_count * 5.0
        else:
            priority = RecommendationPriority.HIGH
            action = (
                f"Clear active backlogs ({bl_count}) at the earliest opportunity to prevent cumulative prerequisite bottlenecks."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 35.0

        if shap_val is not None and shap_val < -0.2:
            ranking_score += abs(shap_val) * 10.0

        impact = self._determine_simulation_impact(sim_delta)
        if impact == ExpectedImpact.UNKNOWN:
            impact = ExpectedImpact.HIGH

        sources = [RecommendationSource.ACADEMIC_DATA, RecommendationSource.RISK_POLICY]
        if shap_val is not None:
            sources.append(RecommendationSource.XAI)
        if sim_delta:
            sources.append(RecommendationSource.WHAT_IF_SIMULATION)
        source = RecommendationSource.COMBINED if len(sources) > 1 else sources[0]

        impact_detail = None
        sim_val = None
        if sim_delta:
            sim_val = sim_delta.get("simulated_value")
            cgpa_diff = sim_delta.get("cgpa_delta", 0.0)
            trans = sim_delta.get("risk_transition", "")
            impact_detail = f"Simulating backlog clearance (to {sim_val}) yields +{cgpa_diff:.2f} predicted CGPA ({trans})."

        evidence = [
            CandidateEvidence(
                factor="backlogs",
                display_name="Active Backlogs",
                current_value=bl_count,
                target_or_threshold=0,
                unit="courses",
                source=source,
                simulated_value=sim_val,
                shap_contribution=shap_val,
                impact_detail=impact_detail,
            )
        ]

        return CandidateRecommendation(
            id="rec-backlog-clearance",
            title="Prioritize Backlog Recovery Plan",
            priority=priority,
            category=RecommendationCategory.BACKLOG_RECOVERY,
            evidence=evidence,
            action=action,
            expected_impact=impact,
            source=source,
            time_horizon=time_horizon,
            risk_factor="Backlogs",
            technical_details={
                "backlog_count": bl_count,
                "shap_contribution": shap_val,
                "simulation_applied": bool(sim_delta),
            },
            ranking_score=ranking_score,
        )


# ---------------------------------------------------------------------------
# Rule 3: Mid-Term Examination Recommendation
# ---------------------------------------------------------------------------

class MidtermExamRecommendationRule(BaseRecommendationRule):
    """
    Evaluates mid-term examination averages (mid_1, mid_2) against institutional targets,
    SHAP contributions, and mid-term improvement simulations.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        m1 = raw_data.get("mid_1")
        m2 = raw_data.get("mid_2")
        if m1 is None or m2 is None:
            return None

        m1_val = float(m1)
        m2_val = float(m2)
        mid_avg = (m1_val + m2_val) / 2.0

        if mid_avg >= RecommendationPolicyConfig.MIDTERM_TARGET:
            return None

        shap_val = self._extract_shap_for_feature(explanation, "mid_1")
        shap_val_2 = self._extract_shap_for_feature(explanation, "mid_2")
        combined_shap = None
        if shap_val is not None or shap_val_2 is not None:
            combined_shap = (shap_val or 0.0) + (shap_val_2 or 0.0)

        sim_delta = simulation_data.get("mid_terms") if simulation_data else None

        if mid_avg < RecommendationPolicyConfig.MIDTERM_CRITICAL_THRESHOLD:
            priority = RecommendationPriority.CRITICAL
            action = (
                f"Your average mid-term examination performance ({mid_avg:.1f}/100) is critically below the institutional benchmark "
                f"({RecommendationPolicyConfig.MIDTERM_CRITICAL_THRESHOLD}). Conduct a comprehensive syllabus review, "
                f"attend faculty office hours, and utilize department tutorial sessions before end-semester finals."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 38.0 + (RecommendationPolicyConfig.MIDTERM_TARGET - mid_avg) * 0.5
        elif mid_avg < RecommendationPolicyConfig.MIDTERM_WARNING_THRESHOLD:
            priority = RecommendationPriority.HIGH
            action = (
                f"Mid-term examination average ({mid_avg:.1f}/100) indicates vulnerability in core coursework. "
                f"Review mid-term question papers, identify low-scoring topics, and complete practice problem sets."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 28.0 + (RecommendationPolicyConfig.MIDTERM_TARGET - mid_avg) * 0.5
        else:
            priority = RecommendationPriority.MEDIUM
            action = (
                f"Mid-term average ({mid_avg:.1f}/100) meets passing standards but falls short of the target benchmark "
                f"({RecommendationPolicyConfig.MIDTERM_TARGET}). Intensify revision on weaker modules to boost final CGPA."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 18.0 + (RecommendationPolicyConfig.MIDTERM_TARGET - mid_avg) * 0.5

        if combined_shap is not None and combined_shap < -0.2:
            ranking_score += abs(combined_shap) * 10.0

        impact = self._determine_simulation_impact(sim_delta)
        if impact == ExpectedImpact.UNKNOWN:
            impact = ExpectedImpact.MEDIUM

        sources = [RecommendationSource.ACADEMIC_DATA, RecommendationSource.RISK_POLICY]
        if combined_shap is not None:
            sources.append(RecommendationSource.XAI)
        if sim_delta:
            sources.append(RecommendationSource.WHAT_IF_SIMULATION)
        source = RecommendationSource.COMBINED if len(sources) > 1 else sources[0]

        impact_detail = None
        sim_val = None
        if sim_delta:
            sim_val = sim_delta.get("simulated_value")
            cgpa_diff = sim_delta.get("cgpa_delta", 0.0)
            trans = sim_delta.get("risk_transition", "")
            impact_detail = f"Simulating mid-term improvement (to {sim_val}) yields +{cgpa_diff:.2f} predicted CGPA ({trans})."

        evidence = [
            CandidateEvidence(
                factor="mid_term_average",
                display_name="Mid-Term Average",
                current_value=round(mid_avg, 1),
                target_or_threshold=RecommendationPolicyConfig.MIDTERM_TARGET,
                unit="marks",
                source=source,
                simulated_value=sim_val,
                shap_contribution=round(combined_shap, 4) if combined_shap is not None else None,
                impact_detail=impact_detail,
            )
        ]

        return CandidateRecommendation(
            id="rec-midterm-preparation",
            title="Strengthen Mid-Term & Exam Preparation",
            priority=priority,
            category=RecommendationCategory.EXAM_PREPARATION,
            evidence=evidence,
            action=action,
            expected_impact=impact,
            source=source,
            time_horizon=time_horizon,
            risk_factor="Mid-Term Performance",
            technical_details={
                "mid_1": m1_val,
                "mid_2": m2_val,
                "mid_avg": mid_avg,
                "combined_shap": combined_shap,
            },
            ranking_score=ranking_score,
        )


# ---------------------------------------------------------------------------
# Rule 4: Internal Assessment Recommendation
# ---------------------------------------------------------------------------

class InternalAssessmentRecommendationRule(BaseRecommendationRule):
    """
    Evaluates continuous internal assessment marks against target benchmarks.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        internal = raw_data.get("internal_marks")
        if internal is None:
            return None

        int_val = float(internal)
        if int_val >= RecommendationPolicyConfig.INTERNAL_TARGET:
            return None

        shap_val = self._extract_shap_for_feature(explanation, "internal_marks")
        sim_delta = simulation_data.get("internal_marks") if simulation_data else None

        if int_val < RecommendationPolicyConfig.INTERNAL_CRITICAL_THRESHOLD:
            priority = RecommendationPriority.HIGH
            action = (
                f"Continuous internal marks ({int_val:.1f}/100) are critically low (< {RecommendationPolicyConfig.INTERNAL_CRITICAL_THRESHOLD}). "
                f"Submit all pending lab assignments, participate actively in continuous evaluations, and request rubric feedback."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 29.0 + (RecommendationPolicyConfig.INTERNAL_TARGET - int_val) * 0.4
        elif int_val < RecommendationPolicyConfig.INTERNAL_WARNING_THRESHOLD:
            priority = RecommendationPriority.MEDIUM
            action = (
                f"Internal assessment marks ({int_val:.1f}/100) are below target ({RecommendationPolicyConfig.INTERNAL_TARGET}). "
                f"Ensure complete and timely assignment submissions and prepare thoroughly for upcoming internal quizzes."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 19.0 + (RecommendationPolicyConfig.INTERNAL_TARGET - int_val) * 0.4
        else:
            priority = RecommendationPriority.LOW
            action = (
                f"Internal marks ({int_val:.1f}/100) are satisfactory. Target consistent full-credit homework and lab work to lock in top grades."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 9.0

        if shap_val is not None and shap_val < -0.2:
            ranking_score += abs(shap_val) * 10.0

        impact = self._determine_simulation_impact(sim_delta)
        if impact == ExpectedImpact.UNKNOWN:
            impact = ExpectedImpact.MEDIUM

        sources = [RecommendationSource.ACADEMIC_DATA, RecommendationSource.RISK_POLICY]
        if shap_val is not None:
            sources.append(RecommendationSource.XAI)
        if sim_delta:
            sources.append(RecommendationSource.WHAT_IF_SIMULATION)
        source = RecommendationSource.COMBINED if len(sources) > 1 else sources[0]

        impact_detail = None
        sim_val = None
        if sim_delta:
            sim_val = sim_delta.get("simulated_value")
            cgpa_diff = sim_delta.get("cgpa_delta", 0.0)
            trans = sim_delta.get("risk_transition", "")
            impact_detail = f"Simulating internal marks boost (to {sim_val}) yields +{cgpa_diff:.2f} predicted CGPA ({trans})."

        evidence = [
            CandidateEvidence(
                factor="internal_marks",
                display_name="Internal Marks",
                current_value=round(int_val, 1),
                target_or_threshold=RecommendationPolicyConfig.INTERNAL_TARGET,
                unit="marks",
                source=source,
                simulated_value=sim_val,
                shap_contribution=shap_val,
                impact_detail=impact_detail,
            )
        ]

        return CandidateRecommendation(
            id="rec-internal-assessment",
            title="Boost Continuous Internal Assessment",
            priority=priority,
            category=RecommendationCategory.INTERNAL_ASSESSMENT,
            evidence=evidence,
            action=action,
            expected_impact=impact,
            source=source,
            time_horizon=time_horizon,
            risk_factor="Internal Assessment",
            technical_details={
                "internal_marks": int_val,
                "shap_contribution": shap_val,
            },
            ranking_score=ranking_score,
        )


# ---------------------------------------------------------------------------
# Rule 5: Academic Trend & CGPA Trajectory Recommendation
# ---------------------------------------------------------------------------

class AcademicTrendRecommendationRule(BaseRecommendationRule):
    """
    Evaluates prior CGPA, predicted CGPA, and semester-over-semester trend.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        prev_cgpa = raw_data.get("previous_cgpa")
        if prev_cgpa is None:
            return None

        prev_val = float(prev_cgpa)
        pred_val = getattr(cgpa_prediction, "predicted_cgpa", None) if cgpa_prediction else None

        # Extract trend from feature summary if available
        trend_val = 0.0
        if cgpa_prediction and hasattr(cgpa_prediction, "feature_summary") and cgpa_prediction.feature_summary:
            trend_val = getattr(cgpa_prediction.feature_summary, "previous_cgpa_trend", 0.0) or 0.0

        shap_val = self._extract_shap_for_feature(explanation, "previous_cgpa")

        # Downward trajectory or low baseline CGPA
        if trend_val < RecommendationPolicyConfig.TREND_SHARP_DROP_THRESHOLD or prev_val < RecommendationPolicyConfig.CGPA_CRITICAL_THRESHOLD:
            priority = RecommendationPriority.HIGH
            action = (
                f"Your academic trajectory reflects a noticeable decline (trend: {trend_val:+.2f}, prior CGPA: {prev_val:.2f}). "
                f"Schedule an academic advising session to review course load balance and study techniques."
            )
            time_horizon = TimeHorizon.THIS_WEEK
            ranking_score = 32.0 + abs(trend_val) * 10.0
            category = RecommendationCategory.STUDY_IMPROVEMENT
        elif trend_val < RecommendationPolicyConfig.TREND_MILD_DROP_THRESHOLD or prev_val < RecommendationPolicyConfig.CGPA_WARNING_THRESHOLD:
            priority = RecommendationPriority.MEDIUM
            action = (
                f"Prior CGPA ({prev_val:.2f}) is below the target benchmark ({RecommendationPolicyConfig.CGPA_TARGET}). "
                f"Set weekly study goals and allocate focused study blocks for heavy-credit core courses."
            )
            time_horizon = TimeHorizon.NEXT_30_DAYS
            ranking_score = 22.0
            category = RecommendationCategory.CGPA_IMPROVEMENT
        else:
            return None

        impact = ExpectedImpact.MEDIUM
        source = RecommendationSource.COMBINED if shap_val is not None else RecommendationSource.ACADEMIC_DATA

        evidence = [
            CandidateEvidence(
                factor="previous_cgpa",
                display_name="Prior CGPA & Trend",
                current_value=round(prev_val, 2),
                target_or_threshold=RecommendationPolicyConfig.CGPA_TARGET,
                unit="points",
                source=source,
                shap_contribution=shap_val,
                impact_detail=f"Semester trend: {trend_val:+.2f} CGPA points.",
            )
        ]

        return CandidateRecommendation(
            id="rec-trajectory-improvement",
            title="Stabilize Academic Performance Trajectory",
            priority=priority,
            category=category,
            evidence=evidence,
            action=action,
            expected_impact=impact,
            source=source,
            time_horizon=time_horizon,
            risk_factor="Academic Trend",
            technical_details={
                "previous_cgpa": prev_val,
                "predicted_cgpa": pred_val,
                "academic_trend": trend_val,
            },
            ranking_score=ranking_score,
        )


# ---------------------------------------------------------------------------
# Rule 6: Strength Maintenance & Advanced Growth Rule
# ---------------------------------------------------------------------------

class StrengthMaintenanceRule(BaseRecommendationRule):
    """
    For high-performing or improving students with zero backlogs and good attendance.
    Ensures balanced recommendations without inventing false critical issues.
    """
    def evaluate(
        self,
        raw_data: Dict[str, Any],
        cgpa_prediction: Optional[Any],
        risk_prediction: Optional[Any],
        explanation: Optional[Any],
        simulation_data: Optional[Dict[str, Any]],
    ) -> Optional[CandidateRecommendation]:
        att = float(raw_data.get("attendance_percentage") or 0.0)
        bl = int(raw_data.get("backlogs") or 0)
        cgpa = float(raw_data.get("previous_cgpa") or 0.0)
        risk_lvl = getattr(risk_prediction, "risk_level", "LOW") if risk_prediction else "LOW"

        # Only applies to strong standing students (LOW or moderate risk with strong indicators)
        if bl == 0 and att >= RecommendationPolicyConfig.ATTENDANCE_SAFE_TARGET and cgpa >= RecommendationPolicyConfig.CGPA_WARNING_THRESHOLD:
            priority = RecommendationPriority.LOW
            action = (
                f"You are maintaining strong academic fundamentals (Attendance: {att:.1f}%, Zero backlogs, "
                f"CGPA: {cgpa:.2f}). Continue your current study routines, explore academic projects or honors coursework, "
                f"and consider peer mentoring opportunities."
            )
            time_horizon = TimeHorizon.LONGER_TERM
            ranking_score = 5.0

            evidence = [
                CandidateEvidence(
                    factor="academic_standing",
                    display_name="Academic Standing",
                    current_value=f"CGPA {cgpa:.2f} · {att:.0f}% Att",
                    target_or_threshold="Maintained",
                    unit="",
                    source=RecommendationSource.ACADEMIC_DATA,
                    impact_detail="Exemplary academic discipline observed across attendance and coursework.",
                )
            ]

            return CandidateRecommendation(
                id="rec-maintain-strength",
                title="Maintain Consistent Academic Momentum",
                priority=priority,
                category=RecommendationCategory.MAINTAIN_STRENGTH,
                evidence=evidence,
                action=action,
                expected_impact=ExpectedImpact.LOW,
                source=RecommendationSource.ACADEMIC_DATA,
                time_horizon=time_horizon,
                risk_factor="Low Risk",
                technical_details={"standing": "strong", "risk_level": risk_lvl},
                ranking_score=ranking_score,
            )

        return None


# Central rule registry
DEFAULT_RULES: List[BaseRecommendationRule] = [
    AttendanceRecommendationRule(),
    BacklogRecommendationRule(),
    MidtermExamRecommendationRule(),
    InternalAssessmentRecommendationRule(),
    AcademicTrendRecommendationRule(),
    StrengthMaintenanceRule(),
]
